global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "backend"
    static_configs:
      - targets: ["backend:8501"]
    metrics_path: /metrics

  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:9464"] 